# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: falco/output/outputs.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66\x61lco/output/outputs.proto\x12\rfalco.outputs\x1a\x1fgoogle/protobuf/timestamp.proto\"\t\n\x07request\"\x8b\x02\n\x08response\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0c\n\x04rule\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x01(\t\x12@\n\routput_fields\x18\x06 \x03(\x0b\x32).falco.outputs.response.OutputFieldsEntry\x12\x0c\n\x04tags\x18\x07 \x03(\t\x12\x10\n\x08hostname\x18\x08 \x01(\t\x1a\x33\n\x11OutputFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x43\n\x07service\x12\x38\n\x03get\x12\x16.falco.outputs.request\x1a\x17.falco.outputs.response0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'falco.output.outputs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSE_OUTPUTFIELDSENTRY']._options = None
  _globals['_RESPONSE_OUTPUTFIELDSENTRY']._serialized_options = b'8\001'
  _globals['_REQUEST']._serialized_start=78
  _globals['_REQUEST']._serialized_end=87
  _globals['_RESPONSE']._serialized_start=90
  _globals['_RESPONSE']._serialized_end=357
  _globals['_RESPONSE_OUTPUTFIELDSENTRY']._serialized_start=306
  _globals['_RESPONSE_OUTPUTFIELDSENTRY']._serialized_end=357
  _globals['_SERVICE']._serialized_start=359
  _globals['_SERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
